name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I was doing X and Y happened...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. See error
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. macOS, Ubuntu
      placeholder: macOS 14.0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: e.g. v0.1.0
      placeholder: v0.1.0
  - type: input
    id: arch
    attributes:
      label: Architecture
      description: e.g. amd64, arm64
      placeholder: amd64
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
